#!/usr/bin/env python3
"""
Simple CSS injection script for VS Code Jupyter notebooks.

This script loads the combined CSS styles and injects them into the notebook
using IPython.display.HTML. This approach works in VS Code Jupyter notebooks
without requiring any extensions.

Usage:
    # In a Jupyter notebook cell:
    %run scripts/inject_notebook_styles.py
    
    # Or import and call:
    from scripts.inject_notebook_styles import inject_styles
    inject_styles()
"""

import os
from pathlib import Path
from IPython.display import HTML, display


def get_combined_css_path():
    """Get the path to the combined CSS file."""
    # Get the project root directory
    current_dir = Path(__file__).parent
    project_root = current_dir.parent
    
    # Look for the combined CSS file
    css_paths = [
        project_root / "assets" / "styles" / "readable_notebook_styles.css",
        project_root / "assets" / "styles" / "notebook_styles.css",
        project_root / "assets" / "styles" / "combined_styles.css",
        project_root / "notebook_styles.css",  # In case it's in root
    ]
    
    for css_path in css_paths:
        if css_path.exists():
            return css_path
    
    # If combined file doesn't exist, create it from individual files
    return create_combined_css()


def create_combined_css():
    """Create a combined CSS file from the readable styles."""
    current_dir = Path(__file__).parent
    project_root = current_dir.parent
    assets_dir = project_root / "assets" / "styles"
    
    # Use the readable styles as the main CSS
    readable_css = assets_dir / "readable_notebook_styles.css"
    
    if readable_css.exists():
        # Just copy the readable styles to notebook_styles.css
        output_path = assets_dir / "notebook_styles.css"
        output_path.write_text(readable_css.read_text(encoding='utf-8'), encoding='utf-8')
        print(f"✅ Created CSS file from readable styles: {output_path}")
        return output_path
    
    # Fallback to original method if readable styles don't exist
    css_files = [
        assets_dir / "custom_markdown.css",
        assets_dir / "custom_classes.css", 
        assets_dir / "custom-callouts.css"
    ]
    
    combined_content = []
    combined_content.append("/* Combined CSS for Jupyter Notebooks */")
    combined_content.append("/* Generated by inject_notebook_styles.py */")
    combined_content.append("")
    
    for css_file in css_files:
        if css_file.exists():
            combined_content.append(f"/* === {css_file.name} === */")
            combined_content.append(css_file.read_text(encoding='utf-8'))
            combined_content.append("")
    
    # Save combined CSS
    output_path = assets_dir / "notebook_styles.css"
    output_path.write_text('\n'.join(combined_content), encoding='utf-8')
    
    print(f"✅ Created fallback combined CSS file: {output_path}")
    return output_path


def inject_styles():
    """Inject CSS styles into the current Jupyter notebook."""
    try:
        css_path = get_combined_css_path()
        
        if not css_path or not css_path.exists():
            print("❌ CSS file not found. Please ensure the CSS files exist in assets/styles/")
            return False
        
        # Read CSS content
        css_content = css_path.read_text(encoding='utf-8')
        
        # Create HTML with embedded CSS
        html_content = f"""
        <style>
        {css_content}
        </style>
        <div class="notebook-styles-injected" style="
            background: var(--color-success-bg, #d1f2eb);
            border: 1px solid var(--color-success-border, #27ae60);
            border-radius: 6px;
            padding: 12px;
            margin: 16px 0;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
            font-size: 14px;
            color: var(--color-success-text, #0f5132);
        ">
            ✅ <strong>Notebook styles successfully injected!</strong><br>
            📁 Loaded from: <code>{css_path.name}</code><br>
            🎨 Your notebook now has enhanced styling for markdown, admonitions, and code cells.
        </div>
        """
        
        # Display the CSS injection
        display(HTML(html_content))
        
        print(f"✅ CSS styles injected from: {css_path}")
        return True
        
    except Exception as e:
        error_html = f"""
        <div style="
            background: #ffebee;
            border: 1px solid #f44336;
            border-radius: 6px;
            padding: 12px;
            margin: 16px 0;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
            font-size: 14px;
            color: #c62828;
        ">
            ❌ <strong>Error injecting styles:</strong><br>
            <code>{str(e)}</code>
        </div>
        """
        display(HTML(error_html))
        print(f"❌ Error injecting styles: {e}")
        return False


def show_style_examples():
    """Display examples of available styling options."""
    examples_html = """
    <div style="margin: 20px 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;">
        <h2>🎨 Available Styling Examples</h2>
        
        <h3>📝 Admonition Boxes</h3>
        <div class="admonition info">
            <div class="admonition-title">ℹ️ Info</div>
            <div class="admonition-content">This is an info admonition box.</div>
        </div>
        
        <div class="admonition warning">
            <div class="admonition-title">⚠️ Warning</div>
            <div class="admonition-content">This is a warning admonition box.</div>
        </div>
        
        <div class="admonition success">
            <div class="admonition-title">✅ Success</div>
            <div class="admonition-content">This is a success admonition box.</div>
        </div>
        
        <div class="admonition error">
            <div class="admonition-title">❌ Error</div>
            <div class="admonition-content">This is an error admonition box.</div>
        </div>
        
        <h3>📊 Markdown Elements</h3>
        <p>Regular text with <strong>bold</strong>, <em>italic</em>, and <code>inline code</code>.</p>
        
        <blockquote>
            This is a styled blockquote with better visual appearance.
        </blockquote>
        
        <h3>🔗 Usage in Markdown Cells</h3>
        <p>In markdown cells, use HTML with these classes:</p>
        <pre><code>&lt;div class="admonition info"&gt;
    &lt;div class="admonition-title"&gt;📌 Note&lt;/div&gt;
    &lt;div class="admonition-content"&gt;Your content here&lt;/div&gt;
&lt;/div&gt;</code></pre>
    </div>
    """
    
    display(HTML(examples_html))


# Auto-inject styles when script is run directly
if __name__ == "__main__":
    print("🎨 Injecting CSS styles into Jupyter notebook...")
    success = inject_styles()
    
    if success:
        print("\n📋 To see styling examples, run:")
        print("    show_style_examples()")
        print("\n🔄 To re-inject styles later, run:")
        print("    inject_styles()")